
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Implement another class for registrations not directly generated by LazyMagic.
// </auto-generated>
//----------------------
namespace ConsumerModule
{
    public static partial class ConsumerModuleRegistrations 
    {
        public static IServiceCollection AddConsumerModule(this IServiceCollection services) 
        {
            services.TryAddSingleton<IConsumerModuleAuthorization, ConsumerModuleAuthorization>();
            services.TryAddSingleton<IConsumerModuleController, ConsumerModuleControllerImpl>();
            services.AddConsumerSchemaRepo();
			services.AddSharedSchemaRepo();
			services.AddStoreSchemaRepo();
            CustomConfigurations(services);
            return services;            
        }
        static partial void CustomConfigurations(IServiceCollection sdervices);
    }
}
