
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace SharedSchemaRepo;
public partial class CategoryEnvelope : DataEnvelope<Category>{}
public partial interface ICategoryRepo : IDYDBRepository<CategoryEnvelope, Category> {}
public partial class CategoryRepo : DYDBRepository<CategoryEnvelope, Category>, ICategoryRepo
{
    public CategoryRepo(IAmazonDynamoDB client) : base(client) {}
}
