
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace SharedSchemaRepo;
public partial class PetEnvelope : DataEnvelope<Pet>{}
public partial interface IPetRepo : IDYDBRepository<PetEnvelope, Pet> {}
public partial class PetRepo : DYDBRepository<PetEnvelope, Pet>, IPetRepo
{
    public PetRepo(IAmazonDynamoDB client) : base(client) {}
}
