
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace SharedSchemaRepo;
public partial class TagEnvelope : DataEnvelope<Tag>{}
public partial interface ITagRepo : IDYDBRepository<TagEnvelope, Tag> {}
public partial class TagRepo : DYDBRepository<TagEnvelope, Tag>, ITagRepo
{
    public TagRepo(IAmazonDynamoDB client) : base(client) {}
}
