AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - 'AWS::Serverless-2016-10-31'
  - 'AWS::LanguageExtensions'
Description: | 
  This stack is used to create tenancy assets
    This includes
      Tenancy Assets bucket
      Tenancy CDNLog Bucket policy
      Tenancy DynamoDb table (note that tables are used like separate databases in DynamoDB)

# Note that this template doesn't allow the deletion of the assets bucket, CDN log bucket, and DynamoDB table
# Also, if the reosurces exist, they are not updated or replaced

Parameters:

  SystemNameParameter:
    Description: "System Name"
    Type: String

  TenantKeyParameter:
    Description: "Tenant Key. No spaces. Lower case."
    Type: String

  # GuidParameter is usually the SystemGuid in the serviceconfig.yaml file
  GuidParameter:
    Description: "GuidParameter"
    Type: String

  CreateAssetsBucketParameter:
    Description: "Create Assets Bucket"
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

  CreateCDNLogBucketParameter:
    Description: "Create CDN Log Bucket"
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

  CreateTenantDBParameter:
    Description: "Create Tenant DB"
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

Conditions:
  CreateAssetsBucket: !Equals [!Ref CreateAssetsBucketParameter, "true"]
  CreateCDNLogBucket: !Equals [!Ref CreateCDNLogBucketParameter, "true"]
  CreateTenantDB: !Equals [!Ref CreateTenantDBParameter, "true"]

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    Condition: CreateAssetsBucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${SystemNameParameter}-assets-${TenantKeyParameter}-${GuidParameter}"

  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateAssetsBucket
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${AssetsBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref AWS::AccountId

  CDNLogBucket:
    Type: AWS::S3::Bucket
    Condition: CreateCDNLogBucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${SystemNameParameter}-cdnlog-${TenantKeyParameter}-${GuidParameter}"
      OwnershipControls:
        Rules: 
          - ObjectOwnership: BucketOwnerPreferred   
      AccessControl: LogDeliveryWrite

  CDNLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateCDNLogBucket
    Properties:
      Bucket: !Ref CDNLogBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${CDNLogBucket}/*"
            Condition:
              StringEquals:
                "s3:x-amz-acl": "bucket-owner-full-control"
          - Effect: "Allow"
            Principal:
              Service: "delivery.logs.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: !Sub "arn:aws:s3:::${CDNLogBucket}"

  # The Tenancy DynamoDb table is used like a separate database in DynamoDB
  # See the LazyMagic documentation for more information on how to use this table
  # with the LazyMagic.DynamoDBRepo library/package.
  TenantDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: CreateTenantDB
    Properties:
      TableName: !Ref TenantKeyParameter
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: SK1
        AttributeType: S
      - AttributeName: SK2
        AttributeType: S
      - AttributeName: SK3
        AttributeType: S
      - AttributeName: SK4
        AttributeType: S
      - AttributeName: SK5
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: PK-SK1-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK1
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK2-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK2
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK3-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK3
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK4-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK4
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK5-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK5
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
        - AttributeName: GSI1PK
          KeyType: HASH
        - AttributeName: GSI1SK
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE

Outputs:
  AssetsBucketName:
    Description: "Config Bucket Name"
    Value: !If
    - CreateAssetsBucket
    - !Ref AssetsBucket
    - !Sub "${SystemNameParameter}-assets-${TenantKeyParameter}-${GuidParameter}"

  CDNLogBucketName:
    Description: "CDN Logs Bucket Name"
    Value: !If
    - CreateCDNLogBucket
    - !Ref CDNLogBucket
    - !Sub "${SystemNameParameter}-cdnlog-${TenantKeyParameter}-${GuidParameter}"

  TenantDBName:
    Description: "Tenant DB Name"
    Value: !If
    - CreateTenantDB
    - !Ref TenantDB
    - !Ref TenantKeyParameter
