openapi: 3.0.1
components:
  schemas:
    Bada:
      type: object
      x-lz-genrepo: true
      properties:
        id:
          type: string
        name:
          type: string    
    Message:
      type: object
      properties:
        id:
          type: string  
        body:
          type: string
        premiseId:
          type: string
        createUtcTick:
          type: integer
          format: int64
        updateUtcTick:
          type: integer
          format: int64
    Premise:
      type: object
      properties:
        id:
          type: string  
        body:
          type: string
        createUtcTick: 
          type: integer
          format: int64
        updateUtcTick:
          type: integer
          format: int64  
