
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace StoreSchemaRepo;
public partial class OrderEnvelope : DataEnvelope<Order>{}
public partial interface IOrderRepo : IDYDBRepository<OrderEnvelope, Order> {}
public partial class OrderRepo : DYDBRepository<OrderEnvelope, Order>, IOrderRepo
{
    public OrderRepo(IAmazonDynamoDB client) : base(client) {}
}
