
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Create your own cs file for this partial class and implement any endpoint methods 
//     not having an x-lz-gencall attribute
// </auto-generated>
//----------------------
namespace SubscriptionsModule
{
    public partial class SubscriptionsModuleControllerImpl : SubscriptionsModuleController
    {
        public SubscriptionsModuleControllerImpl(
            ISubscriptionsModuleAuthorization subscriptionsModuleAuthorization,
			ICategoryRepo categoryRepo,
			ITagRepo tagRepo,
			IPetRepo petRepo,
			IOrderRepo orderRepo,
			ILzNotificationRepo lzNotificationRepo,
			ILzNotificationsPageRepo lzNotificationsPageRepo,
			ILzSubscriptionRepo lzSubscriptionRepo
            ) 
        {
            this.subscriptionsModuleAuthorization = subscriptionsModuleAuthorization;
			this.categoryRepo = categoryRepo;
			this.tagRepo = tagRepo;
			this.petRepo = petRepo;
			this.orderRepo = orderRepo;
			this.lzNotificationRepo = lzNotificationRepo;
			this.lzNotificationsPageRepo = lzNotificationsPageRepo;
			this.lzSubscriptionRepo = lzSubscriptionRepo;

            Init();
        }
    }
}
