
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace ConsumerSchemaRepo;
public partial class PreferencesEnvelope : DataEnvelope<Preferences>{}
public partial interface IPreferencesRepo : IDYDBRepository<PreferencesEnvelope, Preferences> {}
public partial class PreferencesRepo : DYDBRepository<PreferencesEnvelope, Preferences>, IPreferencesRepo
{
    public PreferencesRepo(IAmazonDynamoDB client) : base(client) {}
}
