
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace AdminSchemaRepo;
public partial class TenantUserEnvelope : DataEnvelope<TenantUser>{}
public partial interface ITenantUserRepo : IDYDBRepository<TenantUserEnvelope, TenantUser> {}
public partial class TenantUserRepo : DYDBRepository<TenantUserEnvelope, TenantUser>, ITenantUserRepo
{
    public TenantUserRepo(IAmazonDynamoDB client) : base(client) {}
}
