
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace AdminSchemaRepo;
public partial interface ITenantUserRepo : IDocumentRepo<TenantUser> {}
public partial class TenantUserRepo : DYDBRepository<TenantUser>, ITenantUserRepo
{
    public TenantUserRepo(IAmazonDynamoDB client) : base(client) {}
}
