
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace AdminSchemaRepo;
public partial class UserEnvelope : DataEnvelope<User>{}
public partial interface IUserRepo : IDYDBRepository<UserEnvelope, User> {}
public partial class UserRepo : DYDBRepository<UserEnvelope, User>, IUserRepo
{
    public UserRepo(IAmazonDynamoDB client) : base(client) {}
}
