
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Implement another class for registrations not directly generated by LazyMagic.
// </auto-generated>
//----------------------
namespace LzMessagingModule
{
    public static partial class LzMessagingModuleRegistrations 
    {
        public static IServiceCollection AddLzMessagingModule(this IServiceCollection services) 
        {
            services.TryAddSingleton<ILzMessagingModuleAuthorization, LzMessagingModuleAuthorization>();
            services.TryAddSingleton<ILzMessagingModuleController, LzMessagingModuleControllerImpl>();
            services.AddLzMessagingSchemaRepo();
			services.AddSharedSchemaRepo();
			services.AddStoreSchemaRepo();
            CustomConfigurations(services);
            return services;            
        }
        static partial void CustomConfigurations(IServiceCollection sdervices);
    }
}
