
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace SubscriptionsSchemaRepo;
public partial class LzNotificationEnvelope : DataEnvelope<LzNotification>{}
public partial interface ILzNotificationRepo : IDYDBRepository<LzNotificationEnvelope, LzNotification> {}
public partial class LzNotificationRepo : DYDBRepository<LzNotificationEnvelope, LzNotification>, ILzNotificationRepo
{
    public LzNotificationRepo(IAmazonDynamoDB client) : base(client) {}
}
