
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace SubscriptionsSchemaRepo;
public partial class LzNotificationsPageEnvelope : DataEnvelope<LzNotificationsPage>{}
public partial interface ILzNotificationsPageRepo : IDYDBRepository<LzNotificationsPageEnvelope, LzNotificationsPage> {}
public partial class LzNotificationsPageRepo : DYDBRepository<LzNotificationsPageEnvelope, LzNotificationsPage>, ILzNotificationsPageRepo
{
    public LzNotificationsPageRepo(IAmazonDynamoDB client) : base(client) {}
}
