
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace SubscriptionsSchemaRepo;
public partial class LzSubscriptionEnvelope : DataEnvelope<LzSubscription>{}
public partial interface ILzSubscriptionRepo : IDYDBRepository<LzSubscriptionEnvelope, LzSubscription> {}
public partial class LzSubscriptionRepo : DYDBRepository<LzSubscriptionEnvelope, LzSubscription>, ILzSubscriptionRepo
{
    public LzSubscriptionRepo(IAmazonDynamoDB client) : base(client) {}
}
