
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace WickedSchemaRepo;
public partial interface IBlurbRepo : IDocumentRepo<Blurb> {}
public partial class BlurbRepo : DYDBRepository<Blurb>, IBlurbRepo
{
    public BlurbRepo(IAmazonDynamoDB client) : base(client) {}
}
