
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace WickedSchemaRepo;
public partial interface IChatRepo : IDocumentRepo<Chat> {}
public partial class ChatRepo : DYDBRepository<Chat>, IChatRepo
{
    public ChatRepo(IAmazonDynamoDB client) : base(client) {}
}
