
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Create your own cs file for this partial class and implement any endpoint methods 
//     not having an x-lz-gencall attribute.
//     Note that NSWAG is hardcoded to add 'Controller' to the classname.
// </auto-generated>
//----------------------
namespace StoreModule
{
    public partial class StoreModuleControllerImpl : StoreModuleController
    {
        public StoreModuleControllerImpl(
            IStoreModuleAuthorization storeModuleAuthorization,
			ICategoryRepo categoryRepo,
			ITagRepo tagRepo,
			IPetRepo petRepo,
			IOrderRepo orderRepo,
			IUserRepo userRepo
            ) 
        {
            this.storeModuleAuthorization = storeModuleAuthorization;
			this.categoryRepo = categoryRepo;
			this.tagRepo = tagRepo;
			this.petRepo = petRepo;
			this.orderRepo = orderRepo;
			this.userRepo = userRepo;

            Init();
        }
    }
}
