
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace PublicSchemaRepo;
public partial class BadaEnvelope : DataEnvelope<Bada>{}
public partial interface IBadaRepo : IDYDBRepository<BadaEnvelope, Bada> {}
public partial class BadaRepo : DYDBRepository<BadaEnvelope, Bada>, IBadaRepo
{
    public BadaRepo(IAmazonDynamoDB client) : base(client) {}
}
