
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace PublicSchemaRepo;
public partial interface IMessageRepo : IDocumentRepo<Message> {}
public partial class MessageRepo : DYDBRepository<Message>, IMessageRepo
{
    public MessageRepo(IAmazonDynamoDB client) : base(client) {}
}
