
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Implement another class for registrations not directly generated by LazyMagic.
// </auto-generated>
//----------------------
namespace WickedModule
{
    public static partial class WickedModuleRegistrations 
    {
        public static IServiceCollection AddWickedModule(this IServiceCollection services) 
        {
            services.TryAddSingleton<IWickedModuleAuthorization, WickedModuleAuthorization>();
            services.TryAddSingleton<IWickedModuleController, WickedModuleController>();
            services.AddWickedSchemaRepo();
			services.AddSharedSchemaRepo();
			services.AddStoreSchemaRepo();
            CustomConfigurations(services);
            return services;            
        }
        static partial void CustomConfigurations(IServiceCollection sdervices);
    }
}
