
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Implement another class for registrations not directly generated by LazyMagic.
// </auto-generated>
//----------------------
namespace PublicModule
{
    public static class PublicModuleRegistrations 
    {
        public static IServiceCollection AddPublicModule(this IServiceCollection services) 
        {
            services.TryAddSingleton<IPublicModuleAuthorization, PublicModuleAuthorization>();
            services.TryAddSingleton<IPublicModuleController, PublicModuleControllerImpl>();
            services.AddSharedSchemaRepo();
			services.AddStoreSchemaRepo();
			services.AddSubscriptionsSchemaRepo();
            return services;            
        }
    }
}
