  # WebSocket Api

  __WebSocketApi__:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: __WebSocketApi__
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.eventType

  __WebSocketApi__ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: __WebSocketApi__
      RouteKey: $connect
      AuthorizationType: NONE
      Target:
        Fn::Sub: integrations/${__WebSocketApi__ConnectIntegration}

  __WebSocketApi__ConnectIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: __WebSocketApi__
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${__WebSocketFunction__.Arn}/invocations

  __WebSocketApi__MessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: __WebSocketApi__
      RouteKey: message
      AuthorizationType: NONE
      Target:
        Fn::Sub: integrations/${__WebSocketApi__MessageIntegration}

  __WebSocketApi__MessageIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: __WebSocketApi__
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${__WebSocketFunction__.Arn}/invocations

  __WebSocketApi__DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId:
        Ref: __WebSocketApi__
      RouteKey: $default
      AuthorizationType: NONE
      Target:
        Fn::Sub: integrations/${__WebSocketApi__DefaultIntegration}

  __WebSocketApi__DefaultIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId:
        Ref: __WebSocketApi__
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${__WebSocketFunction__.Arn}/invocations

  __WebSocketApi__Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - __WebSocketApi__MessageRoute
    - __WebSocketApi__ConnectRoute
    - __WebSocketApi__DefaultRoute
    Properties:
      ApiId:
        Ref: __WebSocketApi__

  __WebSocketApi__Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId:
        Ref: __WebSocketApi__
      DeploymentId:
        Ref: __WebSocketApi__Deployment
      StageName:
        Ref: EnvironmentParameter