
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Create your own cs file for this partial class and implement any endpoint methods 
//     not having an x-lz-gencall attribute.
//     Note that NSWAG is hardcoded to add 'Controller' to the classname.
// </auto-generated>
//----------------------
namespace AdminModule
{
    public partial class AdminModuleControllerImpl : AdminModuleController
    {
        public AdminModuleControllerImpl(
            IAdminModuleAuthorization adminModuleAuthorization,
			ICategoryRepo categoryRepo,
			ITagRepo tagRepo,
			IPetRepo petRepo,
			IOrderRepo orderRepo,
			ITenantUserRepo tenantUserRepo
            ) 
        {
            this.adminModuleAuthorization = adminModuleAuthorization;
			this.categoryRepo = categoryRepo;
			this.tagRepo = tagRepo;
			this.petRepo = petRepo;
			this.orderRepo = orderRepo;
			this.tenantUserRepo = tenantUserRepo;

            Init();
        }
    }
}
