
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Implement another class for registrations not directly generated by LazyMagic.
// </auto-generated>
//----------------------
namespace AdminModule
{
    public static partial class AdminModuleRegistrations 
    {
        public static IServiceCollection AddAdminModule(this IServiceCollection services) 
        {
            services.TryAddSingleton<IAdminModuleAuthorization, AdminModuleAuthorization>();
            services.TryAddSingleton<IAdminModuleController, AdminModuleController>();
            services.AddSharedSchemaRepo();
			services.AddStoreSchemaRepo();
			services.AddAdminSchemaRepo();
            CustomConfigurations(services);
            return services;            
        }
        static partial void CustomConfigurations(IServiceCollection sdervices);
    }
}
